### ISSUE TITLE
Preset<object>' has no call signatures.ts

### ISSUE THREAD

**Issue by jojojojojoj5564656465465** [unocss-community/unocss-preset-starter#3]
![image](https://github.com/unpreset/unocss-preset-starter/assets/45184918/97634a9a-76fe-48ad-8914-12a61abea5e6)

Hello, would you be able to tell be why i get this error 
```
This expression is not callable.
  Type 'Preset<object>' has no call signatures.ts(2349)
```

[my npm package](https://www.npmjs.com/package/unocss-preset-wind-extra)

**Comment by screeny05** [comment]
For anyone coming to this thread from google:

My problem was that calling `definePreset` with a callback always returned a type `Preset`, not a `PresetFactory`.

The solution was to make the first argument to the callback optional:

```ts
interface PresetFoobarOptions {}

export const presetLaioutrUi = definePreset((options?: PresetLaioutrUiOptions) => {
  /** [...] */
});
```
